version: '2'
services:
    nginx:
        image: nginx
        ports:
            - '8000:80'
        links:
            - 'app:gunicorn'
        volumes_from:
            - app
        command: /bin/bash -c "cp /code/data/conf/nginx.conf /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    app:
        build: .
        command: ./docker-entrypoint.sh
        environment:
            MALVO_PLATFORM: 'prod'
        volumes:
            - '.:/code'
        depends_on:
            - db
            - cache
        expose:
            - '8001'
    db:
        image: postgres
    cache:
        image: redis
